mqtt.init: use pid file created by mqtt

diff --git a/dist/init.d/mqtt.init b/dist/init.d/mqtt.init
--- a/dist/init.d/mqtt.init
+++ b/dist/init.d/mqtt.init
@@ -13,6 +13,7 @@
 
 set -e
 
+PIDFILE=/var/run/mqtt-lora.pid
 DAEMON=/usr/local/bin/mqtt
 
 # /etc/init.d/mqtt: start and stop the MQTT message parser
@@ -32,44 +33,98 @@ export PATH="${PATH:+$PATH:}/usr/local/bin"
 
 case "$1" in
   start)
-	if init_is_upstart; then
-	    exit 1
-	fi
-	log_daemon_msg "Starting daemon:" "mqtt"
-	if  start-stop-daemon --start --exec ${DAEMON} -- -d ; then
-	    log_end_msg 0
-	else
-	    log_end_msg 1
-	fi
-	;;
+        if init_is_upstart; then
+            exit 1
+        fi
+        log_daemon_msg "Starting network daemon:" "mqtt"
+        if  start-stop-daemon --start --exec ${DAEMON} -- -d ; then
+            log_end_msg 0
+        else
+            log_end_msg 1
+        fi
+        ;;
   stop)
-	if init_is_upstart; then
-	    exit 0
-	fi
-	log_daemon_msg "Stopping daemon:" "mqtt"
-	if start-stop-daemon --stop; then
-	    log_end_msg 0
-	else
-	    log_end_msg 1
-	fi
-	;;
+        if init_is_upstart; then
+            exit 0
+        fi
+        log_daemon_msg "Stopping network daemon:" "mqtt"
+        if start-stop-daemon --stop --pidfile ${PIDFILE}; then
+            log_end_msg 0
+        else
+            log_end_msg 1
+        fi
+        ;;
+
+
+  reload|force-reload)
+        if init_is_upstart; then
+            exit 1
+        fi
+        log_daemon_msg "Reloading network daemon configuration:" "mqtt"
+        if start-stop-daemon --stop --signal HUP --quiet --oknodo --pidfile $PIDFILE; then
+            log_end_msg 0
+        else
+            log_end_msg 1
+        fi
+        ;;
 
   restart)
-	if init_is_upstart; then
-	    exit 1
-	fi
-	log_daemon_msg "Restarting daemon:" "mqtt"
-	start-stop-daemon --stop --quiet --oknodo --retry 30
-	if start-stop-daemon --start --exec ${DAEMON} -- -d ; then
-	    log_end_msg 0
-	else
-	    log_end_msg 1
-	fi
-	;;
+        if init_is_upstart; then
+            exit 1
+        fi
+        log_daemon_msg "Restarting network daemon:" "mqtt"
+        if start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile ${PIDFILE}; then
+            rm -f ${PIDFILE}
+        fi
+        if start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} -- -d -c /etc/lora-mqtt/mqtt.conf ; then
+            log_end_msg 0
+        else
+            log_end_msg 1
+        fi
+        ;;
+
+  try-restart)
+        if init_is_upstart; then
+            exit 1
+        fi
+        log_daemon_msg "Restarting MQTT parser" "mqtt"
+        set +e
+        start-stop-daemon --stop --quiet --retry 30 --pidfile ${PIDFILE}
+        RET="$?"
+        set -e
+        case $RET in
+            0)
+                # old daemon stopped
+                rm -f ${PIDFILE}
+                if start-stop-daemon --start --quiet --oknodo --exec ${DAEMON} ; then
+                    log_end_msg 0
+                else
+                    log_end_msg 1
+                fi
+                ;;
+            1)
+                # daemon not running
+                log_progress_msg "(not running)"
+                log_end_msg 0
+                ;;
+            *)
+                # failed to stop
+                log_progress_msg "(failed to stop)"
+                log_end_msg 1
+                ;;
+        esac
+        ;;
+
+  status)
+        if init_is_upstart; then
+            exit 1
+        fi
+        status_of_proc -p ${PIDFILE} ${DAEMON} mqtt && exit 0 || exit $?
+        ;;
 
   *)
-	log_action_msg "Usage: /etc/init.d/mqtt {start|stop|restart}"
-	exit 1
+        log_action_msg "Usage: /etc/init.d/mqtt {start|stop|reload|force-reload|restart|try-restart|status}"
+        exit 1
 esac
 
 exit 0
